name: WakaTime
on:
  schedule:
    # Runs at 12 am  '0 0 * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          LOCALE: "en"
